services:
  eirbot-eirb-fr-mails:
    image: oia123/formbee-email-only
    container_name: eirbot-eirb-fr-mails
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EMAIL_PROVIDER: ${EMAIL_PROVIDER}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_TO: ${EMAIL_TO}
      ORIGIN: ${ORIGIN}
      SMTP_PORT: ${SMTP_PORT}

  eirbot-eirb-fr-www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eirbot-eirb-fr-www
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${STORE_PORT:-5173}:80'
